### ISSUE TITLE
Fix test which has been skipped

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-element-visibility#21]
Context: https://github.com/Financial-Times/o-element-visibility/pull/18#discussion_r142971778

[This test](https://github.com/Financial-Times/o-element-visibility/blob/master/test/element-visibility.test.js#L98) seems to fail in Chrome, it likely failed for a long time as our automated testing used phantom and this test would exit early if the browser was phantom.

**Comment by rowanmanning** [comment]
We're going to deprecate this component, so we don't care about this any more
